#!/usr/bin/env bash
package=X-UI
package_split=(${package//\// })
package_name=${package_split[-1]}

platforms=(
"linux/386"
"linux/amd64"
"linux/arm"
"linux/arm64"
"linux/mips"
"linux/mips64"
"linux/mips64le"
"linux/mipsle"
"linux/riscv64"
"linux/s390x"
)

for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    output_name=$package_name'-'$GOOS'-'$GOARCH
    if [ $GOOS = "windows" ]; then
        output_name+='.exe'
    fi

    if [ $GOARCH = "arm" ]; then
        echo " "
        echo "###################### arm32v5 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=5 go build -o OUT/"$output_name"32v5 -v -a -ldflags="-linkmode external -extldflags '-static' -s -w" main.go
        echo " "
        echo "###################### arm32v6 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=6 go build -o OUT/"$output_name"32v6 -v -a -ldflags="-linkmode external -extldflags '-static' -s -w" main.go
        echo " "
        echo "###################### arm32v7 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=7 go build -o OUT/"$output_name"32v7 -v -a -ldflags="-linkmode external -extldflags '-static' -s -w" main.go
    else
        echo " "
        echo "###################### $GOARCH ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH go build -o OUT/$output_name -v -a -ldflags="-linkmode external -extldflags '-static' -s -w" main.go
    fi


    if [ $? -ne 0 ]; then
           echo 'An error has occurred! Aborting the script execution...'
        exit 1
    fi
done
