#!/usr/bin/env bash
package=XrayR
package_split=(${package//\// })
package_name=${package_split[-1]}

platforms=(
"aix/ppc64"
"android/386"
"android/amd64"
"android/arm"
"android/arm64"
"darwin/amd64"
"darwin/arm64"
"dragonfly/amd64"
"freebsd/386"
"freebsd/amd64"
"freebsd/arm"
"freebsd/arm64"
"illumos/amd64"
"ios/amd64"
"ios/arm64"
"js/wasm"
"linux/386"
"linux/amd64"
"linux/arm"
"linux/arm64"
"linux/mips"
"linux/mips64"
"linux/mips64le"
"linux/mipsle"
"linux/ppc64"
"linux/ppc64le"
"linux/riscv64"
"linux/s390x"
"netbsd/386"
"netbsd/amd64"
"netbsd/arm"
"netbsd/arm64"
"openbsd/386"
"openbsd/amd64"
"openbsd/arm"
"openbsd/arm64"
"openbsd/mips64"
"plan9/386"
"plan9/amd64"
"plan9/arm"
"solaris/amd64"
"windows/386"
"windows/amd64"
"windows/arm"
)

for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    output_name=$package_name'-'$GOOS'-'$GOARCH
    if [ $GOOS = "windows" ]; then
        output_name+='.exe'
    fi

    if [ $GOARCH=arm ]; then
        echo " "
        echo "###################### arm32v5 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=5 go build -o OUT/"$output_name"32v5 -v -trimpath -ldflags "-s -w -buildid=" ./main
        echo " "
        echo "###################### arm32v6 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=6 go build -o OUT/"$output_name"32v6 -v -trimpath -ldflags "-s -w -buildid=" ./main
        echo " "
        echo "###################### arm32v7 ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=7 go build -o OUT/"$output_name"32v7 -v -trimpath -ldflags "-s -w -buildid=" ./main
    else
        echo " "
        echo "###################### $GOARCH ######################"
        echo " "
        env GOOS=$GOOS GOARCH=$GOARCH go build -o OUT/$output_name -v -trimpath -ldflags "-s -w -buildid=" ./main
    fi

    if [ $? -ne 0 ]; then
           echo 'An error has occurred! Aborting the script execution...'
        exit 1
    fi
done
